### ISSUE TITLE
I am not able to get this to work

### ISSUE THREAD

**Issue by mrelarsen** [8ctopus/pysciter-example#1]
My steps on windows:
Download zip and extract
Open promt of choice (if powershell use semicolon instead of &&)
Run `cd <extracted folder path> && py -m venv .`
Click on activate.bat in the generated Scripts folder
Run `cd <extracted folder path>/Scripts/ && pip install pysciter`
Click on the install.bat in extracted folder
Run  `cd <extracted folder path>/Scripts/ && python ../example.py`

Oneliner:
Run `cd <extracted folder path> && py -m venv . && cd Scripts && start "" /W activate.bat && pip install pysciter && start "" /D .. /W install.bat && python ../example.py`

Error:
Traceback (most recent call last):
  File "C:\Users\xxx\Desktop\pysciter-example-master\example.py", line 3, in <module>
    import sciter
  File "C:\Users\xxx\Desktop\pysciter-example-master\lib\site-packages\sciter\__init__.py", line 22, in <module>
    from .value import value as Value
  File "C:\Users\xxx\Desktop\pysciter-example-master\lib\site-packages\sciter\value.py", line 14, in <module>
    _api = sciter.SciterAPI()
  File "C:\Users\xxx\Desktop\pysciter-example-master\lib\site-packages\sciter\capi\scapi.py", line 583, in SciterAPI
    raise ImportError(SCITER_LOAD_ERROR + "\n" + "\n".join(errors))
ImportError: sciter.dll was not found in PATH.
  Please verify that Sciter SDK is installed and its binaries (SDK/bin, bin.osx or bin.gtk) are available in the path.
'sciter': Could not find module 'sciter' (or one of its dependencies). Try using the full path with constructor syntax.
'sciter64.dll': Could not find module 'sciter64.dll' (or one of its dependencies). Try using the full path with constructor syntax.

**Comment by mrelarsen** [comment]
I had to add sciter to System32

**Comment by 8ctopus** [comment]
Hello!

It looks like you missed the sciter installation step from the README: https://github.com/8ctopus/pysciter-example/blob/108606483f54e5fc5f58a79b92aa6369c9fa83f5/README.md?plain=1#L12

Which would explain why it didn't work in the first place.

**Comment by mrelarsen** [comment]
Isn't that exactly what I do in line `Click on the install.bat in extracted folder` or `start "" /D .. /W install.bat`

**Comment by 8ctopus** [comment]
@mrelarsen Sorry about that, important is that you got it to work.
